// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Railway: internal hostname only works inside their network. Use public proxy locally.
    url:
      process.env["DATABASE_PUBLIC_URL"]?.trim() ||
      process.env["DATABASE_URL"],
  },
});
